create extension if not exists citext;
create extension if not exists pgcrypto;

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at := now();
    return new;
end;
$$;

create table if not exists app_user (
    id bigint generated by default as identity primary key,
    full_name text,
    email citext not null unique,
    role text not null default 'member',
    active boolean not null default true,
    pin_hash text,
    pin_fingerprint text unique,
    pin_attempts integer not null default 0,
    locked_until timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint app_user_pin_attempts_nonnegative check (pin_attempts >= 0)
);

create index if not exists app_user_pin_fingerprint_idx on app_user (pin_fingerprint);
create index if not exists app_user_active_idx on app_user (active);

drop trigger if exists trg_app_user_updated_at on app_user;
create trigger trg_app_user_updated_at
before update on app_user
for each row
execute function set_updated_at();

create table if not exists booking_action_audit (
    id bigint generated by default as identity primary key,
    action text not null,
    room_email text not null,
    starts_at timestamptz,
    ends_at timestamptz,
    app_user_id bigint not null references app_user(id) on delete restrict,
    meta jsonb,
    created_at timestamptz not null default now()
);

create index if not exists booking_action_audit_app_user_id_idx
    on booking_action_audit (app_user_id);
create index if not exists booking_action_audit_room_email_idx
    on booking_action_audit (room_email);
create index if not exists booking_action_audit_created_at_idx
    on booking_action_audit (created_at desc);

create or replace function verify_app_user_pin(
    p_app_user_id bigint,
    p_pin text
)
returns boolean
language plpgsql
as $$
declare
    user_row app_user%rowtype;
begin
    if p_pin is null or p_pin !~ '^\d{4,8}$' then
        return false;
    end if;

    select *
    into user_row
    from app_user
    where id = p_app_user_id;

    if not found then
        return false;
    end if;

    if not user_row.active then
        return false;
    end if;

    if user_row.locked_until is not null and user_row.locked_until > now() then
        return false;
    end if;

    if user_row.pin_hash is null then
        return false;
    end if;

    if crypt(p_pin, user_row.pin_hash) = user_row.pin_hash then
        update app_user
        set pin_attempts = 0,
            locked_until = null
        where id = user_row.id;

        return true;
    end if;

    update app_user
    set pin_attempts = pin_attempts + 1,
        locked_until = case
            when pin_attempts + 1 >= 5 then now() + interval '15 minutes'
            else locked_until
        end
    where id = user_row.id;

    return false;
end;
$$;

create or replace function login_by_pin(
    p_pin text,
    p_pepper text
)
returns table (
    app_user_id bigint,
    full_name text,
    role text,
    email citext
)
language plpgsql
as $$
declare
    v_fingerprint text;
begin
    if p_pin is null or p_pin !~ '^\d{4,8}$' then
        return;
    end if;

    if p_pepper is null or length(p_pepper) = 0 then
        raise exception 'PIN pepper is required';
    end if;

    v_fingerprint := encode(digest(p_pepper || ':' || p_pin, 'sha256'), 'hex');

    update app_user
    set pin_attempts = 0,
        locked_until = null
    where pin_fingerprint = v_fingerprint
      and active = true
      and (locked_until is null or locked_until <= now())
      and pin_hash is not null
      and crypt(p_pin, pin_hash) = pin_hash;

    return query
    select u.id, u.full_name, u.role, u.email
    from app_user u
    where u.pin_fingerprint = v_fingerprint
      and u.active = true
      and (u.locked_until is null or u.locked_until <= now())
      and u.pin_hash is not null
      and crypt(p_pin, u.pin_hash) = u.pin_hash
    limit 1;
end;
$$;

create or replace function set_app_user_pin(
    p_app_user_id bigint,
    p_pin text,
    p_pepper text
)
returns void
language plpgsql
as $$
declare
    v_fingerprint text;
    v_hash text;
begin
    if p_pin is null or p_pin !~ '^\d{4,8}$' then
        raise exception 'PIN must be 4-8 digits';
    end if;

    if p_pepper is null or length(p_pepper) = 0 then
        raise exception 'PIN pepper is required';
    end if;

    if not exists (select 1 from app_user where id = p_app_user_id) then
        raise exception 'app_user % does not exist', p_app_user_id;
    end if;

    v_fingerprint := encode(digest(p_pepper || ':' || p_pin, 'sha256'), 'hex');
    v_hash := crypt(p_pin, gen_salt('bf'));

    update app_user
    set pin_hash = v_hash,
        pin_fingerprint = v_fingerprint,
        pin_attempts = 0,
        locked_until = null
    where id = p_app_user_id;
end;
$$;
